/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package worldeditor;

import java.awt.Font;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import static worldeditor.WorldEditor.guardado;
import static worldeditor.WorldEditor.nombreArchivo;
import static worldeditor.WorldEditor.paneltexto;

/**
 * Guarda el mapa en 
 * @author jesus
 */
public class GuardarComo extends javax.swing.JFrame {

    /**
     * Creates new form GuardarComo
     */
    public GuardarComo() {
        initComponents();
        setTitle("Guardar Como:");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoTexto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        aceptarB = new javax.swing.JButton();
        cancelarB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTextoKeyTyped(evt);
            }
        });

        jLabel1.setText("Nombre de Archivo:");

        aceptarB.setText("Aceptar");
        aceptarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBActionPerformed(evt);
            }
        });

        cancelarB.setText("Cancelar");
        cancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aceptarB)
                        .addGap(102, 102, 102)
                        .addComponent(cancelarB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(campoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarB)
                    .addComponent(cancelarB))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBActionPerformed


        if (guardado == 1) {
            StringTokenizer token = new StringTokenizer(paneltexto, "\n");
        nombreNuevo = campoTexto.getText() + ".txt";
        FileWriter fichero = null;

        PrintWriter pw = null;
            try {
                

                fichero = new FileWriter(nombreNuevo);

                pw = new PrintWriter(fichero);

                while (token.hasMoreTokens()) {
                    pw.println(token.nextToken());
                }

                JOptionPane.showMessageDialog(null, "¡Archivo guardado con Éxito!");

            } catch (Exception e) {

                e.printStackTrace();

            } finally {

                try {

                    if (null != fichero) {
                        fichero.close();
                    }

                } catch (Exception e2) {

                    e2.printStackTrace();

                }

            }
            dispose();
        } 
        if (guardado == 2) {
           StringTokenizer token = new StringTokenizer(paneltexto, "\n");
        nombreNuevo = campoTexto.getText() + ".txt";
        FileWriter fichero = null;

        PrintWriter pw = null;
            try {
                fichero = new FileWriter(nombreNuevo);

                pw = new PrintWriter(fichero);

                while (token.hasMoreTokens()) {
                    pw.println(token.nextToken().toUpperCase());
                }

                JOptionPane.showMessageDialog(null, "¡Archivo en mayusculas guardado con Éxito!");

            } catch (Exception e) {

                e.printStackTrace();

            } finally {

                try {

                   
                    if (null != fichero) {
                        fichero.close();
                    }

                } catch (Exception e2) {

                    e2.printStackTrace();

                }

            }
            dispose();
        }
        if (guardado==3) {
           StringTokenizer token = new StringTokenizer(paneltexto, "\n");
        nombreNuevo = campoTexto.getText() + ".txt";
        FileWriter fichero = null;

        PrintWriter pw = null;
            try {

                fichero = new FileWriter(nombreNuevo);

                pw = new PrintWriter(fichero);

                while (token.hasMoreTokens()) {
                    pw.println(token.nextToken().toLowerCase());
                }

                JOptionPane.showMessageDialog(null, "¡Archivo en minusculas guardado con Éxito!");

            } catch (Exception e) {

                e.printStackTrace();

            } finally {

                try {

                    
                    if (null != fichero) {
                        fichero.close();
                    }

                } catch (Exception e2) {

                    e2.printStackTrace();

                }

            }
            dispose();
        }

    }//GEN-LAST:event_aceptarBActionPerformed

    private void cancelarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelarBActionPerformed
    /**
     * Metodo de tecla presionada, que valida lque solo pueden introducirse
     * letras dentro del campo de texto.
     *
     * @param evt evento al que escucha
     */
    private void campoTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTextoKeyTyped
        char caracter = evt.getKeyChar();
        // TODO add your handling code here:
        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter != (char) KeyEvent.VK_ENTER) && (caracter != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se admite texto", "Validar texto", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_campoTextoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuardarComo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuardarComo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuardarComo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuardarComo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuardarComo().setVisible(true);
            }
        });
    }

    public static String nombreNuevo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarB;
    private javax.swing.JTextField campoTexto;
    private javax.swing.JButton cancelarB;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
